name: website_blocker
description: An app to block websites and filter content based on keywords
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  flutter_vpn: ^0.13.0  # For VPN functionality
  webview_flutter: ^4.2.0 # For the embedded safe browser

  permission_handler: ^10.4.3
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  flutter_local_notifications: ^14.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true